/* Auto-generated by psvita-toolkit -- see generated_jni_table.h */
#include <falso_jni/FalsoJNI_Impl.h>
#include "generated_jni_table.h"

// ---- com.flukedude.impossiblegame.ImpossibleGame ----
jobject stub_ImpossibleGame_ImpossibleGame_0(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.ImpossibleGame(Lcom.flukedude.impossiblegame.ImpossibleGameActivity;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

jint stub_ImpossibleGame_a_1(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.a(LContext;LGL10;IILBitmap.Config;)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg2 = (jint) va_arg(args, int);
    jint arg3 = (jint) va_arg(args, int);
    jobject arg4 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return 0;
}

void stub_ImpossibleGame_a_2(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.a(LGL10;Z)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jboolean arg1 = (jboolean) va_arg(args, int);
}

void stub_ImpossibleGame_d_3(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.d()V called -- fill in from the real Java impl (jadx).");
}

void stub_ImpossibleGame_e_4(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.e()V called -- fill in from the real Java impl (jadx).");
}

void stub_ImpossibleGame_f_5(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.f()V called -- fill in from the real Java impl (jadx).");
}

void stub_ImpossibleGame_a_6(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.a()V called -- fill in from the real Java impl (jadx).");
}

void stub_ImpossibleGame_a_7(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.a(F)V called -- fill in from the real Java impl (jadx).");
    jfloat arg0 = (jfloat) va_arg(args, double);
}

void stub_ImpossibleGame_a_8(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.a(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_ImpossibleGame_a_9(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.a(IZ)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jboolean arg1 = (jboolean) va_arg(args, int);
}

void stub_ImpossibleGame_a_10(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.a(LSharedPreferences;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_ImpossibleGame_b_11(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.b()V called -- fill in from the real Java impl (jadx).");
}

void stub_ImpossibleGame_b_12(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.b(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_ImpossibleGame_c_13(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.c()V called -- fill in from the real Java impl (jadx).");
}

void stub_ImpossibleGame_c_14(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.c(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_ImpossibleGame_onDrawFrame_15(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.onDrawFrame(LGL10;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_ImpossibleGame_onSurfaceChanged_16(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.onSurfaceChanged(LGL10;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_ImpossibleGame_onSurfaceCreated_17(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.flukedude.impossiblegame.ImpossibleGame.onSurfaceCreated(LGL10;LEGLConfig;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

