/* Auto-generated by psvita-toolkit from decompiled/apk_jadx/sources -- FalsoJNI callback candidates. */
/* Every entry here is a CANDIDATE: confirm the method belongs on the .so's actual call path, and */
/* read the real Java implementation (jadx) before trusting the stub body. See docs/dev-notes/jni_analyzer.md. */
#pragma once
#include <stdarg.h>
#include <falso_jni/FalsoJNI_Impl.h>

extern jobject stub_ImpossibleGame_ImpossibleGame_0(jmethodID id, va_list args);
extern jint stub_ImpossibleGame_a_1(jmethodID id, va_list args);
extern void stub_ImpossibleGame_a_2(jmethodID id, va_list args);
extern void stub_ImpossibleGame_d_3(jmethodID id, va_list args);
extern void stub_ImpossibleGame_e_4(jmethodID id, va_list args);
extern void stub_ImpossibleGame_f_5(jmethodID id, va_list args);
extern void stub_ImpossibleGame_a_6(jmethodID id, va_list args);
extern void stub_ImpossibleGame_a_7(jmethodID id, va_list args);
extern void stub_ImpossibleGame_a_8(jmethodID id, va_list args);
extern void stub_ImpossibleGame_a_9(jmethodID id, va_list args);
extern void stub_ImpossibleGame_a_10(jmethodID id, va_list args);
extern void stub_ImpossibleGame_b_11(jmethodID id, va_list args);
extern void stub_ImpossibleGame_b_12(jmethodID id, va_list args);
extern void stub_ImpossibleGame_c_13(jmethodID id, va_list args);
extern void stub_ImpossibleGame_c_14(jmethodID id, va_list args);
extern void stub_ImpossibleGame_onDrawFrame_15(jmethodID id, va_list args);
extern void stub_ImpossibleGame_onSurfaceChanged_16(jmethodID id, va_list args);
extern void stub_ImpossibleGame_onSurfaceCreated_17(jmethodID id, va_list args);

// Candidate NameToMethodID entries -- append into the real nameToMethodId[] in java.c
static const NameToMethodID generated_nameToMethodId[] = {
    { 0, "ImpossibleGame", METHOD_TYPE_OBJECT },  // com.flukedude.impossiblegame.ImpossibleGame
    { 1, "a", METHOD_TYPE_INT },  // com.flukedude.impossiblegame.ImpossibleGame
    { 2, "a", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 3, "d", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 4, "e", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 5, "f", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 6, "a", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 7, "a", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 8, "a", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 9, "a", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 10, "a", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 11, "b", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 12, "b", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 13, "c", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 14, "c", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 15, "onDrawFrame", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 16, "onSurfaceChanged", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
    { 17, "onSurfaceCreated", METHOD_TYPE_VOID },  // com.flukedude.impossiblegame.ImpossibleGame
};

// Candidate methodsObject[] entries -- append into the real methodsObject[] in java.c
static const MethodsObject generated_methodsObject[] = {
    { 0, stub_ImpossibleGame_ImpossibleGame_0 },
};

// Candidate methodsInt[] entries -- append into the real methodsInt[] in java.c
static const MethodsInt generated_methodsInt[] = {
    { 1, stub_ImpossibleGame_a_1 },
};

// Candidate methodsVoid[] entries -- append into the real methodsVoid[] in java.c
static const MethodsVoid generated_methodsVoid[] = {
    { 2, stub_ImpossibleGame_a_2 },
    { 3, stub_ImpossibleGame_d_3 },
    { 4, stub_ImpossibleGame_e_4 },
    { 5, stub_ImpossibleGame_f_5 },
    { 6, stub_ImpossibleGame_a_6 },
    { 7, stub_ImpossibleGame_a_7 },
    { 8, stub_ImpossibleGame_a_8 },
    { 9, stub_ImpossibleGame_a_9 },
    { 10, stub_ImpossibleGame_a_10 },
    { 11, stub_ImpossibleGame_b_11 },
    { 12, stub_ImpossibleGame_b_12 },
    { 13, stub_ImpossibleGame_c_13 },
    { 14, stub_ImpossibleGame_c_14 },
    { 15, stub_ImpossibleGame_onDrawFrame_15 },
    { 16, stub_ImpossibleGame_onSurfaceChanged_16 },
    { 17, stub_ImpossibleGame_onSurfaceCreated_17 },
};

